"""add_conversation_summary

Revision ID: 53695095a4f5
Revises: 4d882c62b11e
Create Date: 2026-04-26 15:54:05.211313
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "53695095a4f5"
down_revision: str | None = "4d882c62b11e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("users")]
    if "conversation_summary" not in columns:
        op.add_column(
            "users", sa.Column("conversation_summary", sa.Text(), nullable=True)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c["name"] for c in inspector.get_columns("users")]
    if "conversation_summary" in columns:
        op.drop_column("users", "conversation_summary")
    # ### end Alembic commands ###
