"""add_legal_consent

Revision ID: a748b9764cce
Revises: 6f83dfe53f05
Create Date: 2026-05-26 06:56:27.358559
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a748b9764cce"
down_revision: str | None = "6f83dfe53f05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "has_consented", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column(
        "users", sa.Column("consented_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "consented_at")
    op.drop_column("users", "has_consented")
    # ### end Alembic commands ###
